"""
    Problem Statement Name : Even Fibonacci numbers
    
    Description : 
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        
    Answer : 4613732

"""

from typing import Generator


def fibonacci_range(end_point: int) -> Generator[int, int, int]:
    
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a+b
        if a >= end_point:
            break
            
                          
    
def solution(fib_range: int) -> int:
    
    return sum([x for x in fibonacci_range(fib_range) if x%2 == 0])
    
    
if __name__ == '__main__':
    
    print(solution(fib_range = 4_000_000))
    